Allow specifying failoverTimeMillis property for Kinesis consumer
A worker which does not renew it's lease within this time interval
will be regarded as having problems and it's shards will be assigned
to other workers.

Increasing failoverTimeMillis is suggested by AWS Support Team
to avoid following issue:
```
java.lang.RuntimeException: java.lang.InterruptedException at
software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.
getRecords(KinesisDataFetcher.java:336
```

Bug: Issue 287304308
Change-Id: I9dbb79399d17b01e09d4cb672e83915b1909ec31